name: netplayer_lite
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  audio_service: ^0.18.10
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.1.0
  just_audio: ^0.9.35
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/